name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_banking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install CMake 
      run: |
           git submodule init && git submodule update
           sudo apt update -y
           sudo apt install -y cmake
